name: hue_craft
description: You can build your own custom color pickers easily with this package
version: 0.0.3
homepage: https://github.com/HARUM1122/hue_craft

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  skein_color_convert: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0