name: hue_craft
description: You can build your own custom color pickers easily with this package
version: 0.0.7
homepage: https://github.com/HARUM1122/hue_craft

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0