name: hue_craft
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/HARUM1122/hue_craft

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  skein_color_convert: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  assets:
    - assets/images/checker_board_pattern.jpg